### ISSUE TITLE
Generic build of Blendtronic incompatibility with generic Hodgepodge

### ISSUE THREAD

**Issue by SilearFlare** [GTMEGA/Blendtronic#6]
Tested a barebone 1.7 instance with nothing but Hodgepodge and the latest release of Blendtronic.

https://paste.ee/p/NT5Bk

Hodgepodge repo
https://github.com/GTNewHorizons/Hodgepodge

Edit:
It seems that both mods are trying to do the same thing, but Blendtronic currently lacks a configuration file to disable this feature.
The issue (and similar ones that may arise with other mod mixin interactions currently or in the future) could easily be fixed by creating a config file automatically and letting the user disable them at will, should they encounter a conflict.

Thank you in advance for your time and any help on the subject.

**Comment by makamys** [comment]
It looks like `CommonProxy` is never referenced anywhere, which is where the code for creating the config file would be called.

**Comment by SirFell** [comment]
Blendtronic is not meant to be used alongside hodgepodge for general public, configuration doesnt exist either since as of right now its meant to apply all fixes. 

Version compatible with hodgepodge will be released exclusively for Zvezdolet server and doesnt come with permission to modify and redistribute modified code in any way shape or form with exception of personal use.

@tyrael93 i will provide a build with hodgepodge's mixins in mind in Zvezdolets discord in next day or two, thanks for saving me some time checking current hodgepodge src.

**Comment by SirFell** [comment]
To clarify it again: license for this mod is CC:BY-ND and even Zvezdolet must abide by it.

**Comment by SilearFlare** [comment]
Alright that seems pretty straightforward, I think I can close this one then!

Just as a quick afterthought: what or who is a zvezdolet exactly?
Because I literally just came here because I tend to add all the 1.7 mixin mods I can find and I have no idea who this fellow might be or, in fact, where to actually download the compatible mod that will be posted therein since I don't see any discord links in the repo

**Comment by SirFell** [comment]
@tyrael93 one of unofficial servers on the official gtnh server list, if you have the need of the mod yourself you can request it with more detailed 'why' in our discord (invite in gtmega repo) or SirFell#1024 
if you want it for gtnh - you likely dont need it as its more or less hodgepodge minus things unneeded in gtmega, as an added bonus - its unaffiliated with gtnh people and thus wont sneakily change license from MIT to GPL for no good reason and without asking other contributors for permission
